name: XtendDemo
main: de.dustplanet.xtenddemo.XtendDemo
version: 0.0.1
author: xGhOsTkiLLeRx
website: https://github.com/timbru31/bukkit-xtend-demo
api-version: 1.15
commands:
  xtend:
    description: Greets all online players
    usage: /xtend - unleashes the Xtend power!
